In [1]:
import numpy as np
import pandas as pd
import pylab as pl

import matplotlib.pyplot as plt

import sklearn
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler as scale

import sklearn.metrics as sm
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
apps  = pd.read_pickle('C:\\Users\\luken\\Documents\\Home Credit Group\\Data\\train_only_app_features.pkl')
apps.sample(10)

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_0,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
161789,0,0,157500.0,588874.5,21280.5,414000.0,0.019689,-19983,-10731,-12567.0,...,0,0,0,0,0,0,0,1,0,0
396871,0,0,225000.0,450000.0,23562.0,450000.0,0.014464,-19050,-112,-9144.0,...,0,0,0,0,1,0,0,0,1,0
388821,0,1,81000.0,604152.0,29196.0,540000.0,0.031329,-14136,-2758,-3293.0,...,0,0,0,0,1,0,0,0,1,0
304957,0,0,495000.0,1085994.0,52375.5,877500.0,0.032561,-18145,-677,-1390.0,...,0,0,0,0,0,1,0,0,1,0
344337,0,0,292500.0,1288350.0,37800.0,1125000.0,0.018801,-20572,-5138,-9189.0,...,0,0,0,0,0,0,0,1,0,0
259117,0,0,180000.0,302206.5,13441.5,229500.0,0.016612,-11972,-1361,-393.0,...,0,0,0,0,0,1,0,0,1,0
194613,0,0,270000.0,673875.0,17775.0,562500.0,0.030755,-15961,-641,-9903.0,...,0,0,0,0,0,1,0,0,1,0
247251,0,2,157500.0,855000.0,25128.0,855000.0,0.015221,-15052,-2620,-7292.0,...,0,0,0,0,0,1,0,0,1,0
375370,0,0,225000.0,1096020.0,52857.0,900000.0,0.010032,-10895,-1076,-2915.0,...,0,0,0,0,0,0,0,1,0,0
448098,0,1,400500.0,1129500.0,31059.0,1129500.0,0.030755,-11789,-2343,-6065.0,...,0,0,0,0,0,0,0,1,0,0

# One Hot Encoding
Transform catagorical to binary dummies

In [3]:
# Encode the catgorical varibles with one hot 
def one_hot_encode_it(dset):

    print('The following varibles have been one hot encoded.')
    for column in dset.columns:
        if dset[column].dtype == type(object):
            x = pd.get_dummies(dset[column],prefix=column)
            dset = dset.join(x,on='SK_ID_CURR').drop(str(column),1)
            del x
            print(column)
    return dset

apps = one_hot_encode_it(apps)
apps.sample(10)

The following varibles have been one hot encoded.

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_0,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
438967,0,1,81000.0,814041.0,23931.0,679500.0,0.031329,-10477,-2748,-4730.0,...,0,0,0,0,0,0,0,1,0,0
276151,0,0,135000.0,900000.0,26446.5,900000.0,0.006852,-15789,-1889,-4899.0,...,0,0,0,0,0,0,0,1,0,0
256301,1,0,90000.0,254700.0,14620.5,225000.0,0.007120,-22579,365243,-13871.0,...,0,0,0,0,0,0,0,1,0,0
348241,0,0,135000.0,285453.0,15615.0,193500.0,0.010500,-15638,-985,-510.0,...,0,0,0,0,0,0,0,1,0,0
174534,0,0,180000.0,1078200.0,31653.0,900000.0,0.046220,-23342,365243,-56.0,...,0,0,0,0,0,0,0,1,0,0
181534,0,0,135000.0,405000.0,19827.0,405000.0,0.002042,-9015,-266,-2510.0,...,0,0,0,0,0,0,0,1,0,0
244712,0,0,315000.0,454500.0,23337.0,454500.0,0.009657,-11975,-1501,-3156.0,...,0,0,0,0,0,0,0,1,0,0
399846,0,1,76500.0,521280.0,27423.0,450000.0,0.016612,-13859,-1167,-6236.0,...,0,0,0,0,0,0,0,1,0,0
153050,0,0,225000.0,448056.0,21789.0,315000.0,0.007274,-20380,365243,-6139.0,...,0,0,0,0,0,1,0,0,1,0
323997,0,0,207000.0,2250000.0,59355.0,2250000.0,0.019101,-14424,-178,-5520.0,...,0,0,0,0,0,1,0,0,1,0

# Scale data
Scale the input data to avoid large value dominating the euclidian space calculation

In [8]:
## Baisc data check to confirm that data has no NAN (missings) or infinity values
# np.any(np.isnan(apps))
np.any(np.isfinite(apps))
# apps = apps.fillna(0)
# 
# print(apps.loc[[445398]])


scaled_app = scale(apps)
# NOTE: Scaled_app is not longer a pandas dataframe, it is not a numpy array
scaled_app[:10]

array([[ 3.37448515, -0.57753784,  0.14212925, ..., -0.94925202,
         0.96376312, -0.08733962],
       [-0.2963415 , -0.57753784,  0.42679193, ..., -0.94925202,
         0.96376312, -0.08733962],
       [-0.2963415 , -0.57753784, -0.4271961 , ...,  1.05346102,
        -1.03759936, -0.08733962],
       ...,
       [-0.2963415 , -0.57753784,  0.80634217, ...,  1.05346102,
        -1.03759936, -0.08733962],
       [-0.2963415 , -0.57753784, -0.23742098, ...,  1.05346102,
        -1.03759936, -0.08733962],
       [-0.2963415 , -0.57753784, -0.14253343, ...,  1.05346102,
        -1.03759936, -0.08733962]])

# Builing and running the model

In [ ]:

Nc = range(2, 30)

kmeans = [KMeans(n_clusters=i) for i in Nc]

kmeans

score = [kmeans[i].fit(scaled_app).score(scaled_app) for i in range(len(kmeans))]

print(list(Nc))

print(score)

plt.plot(list(Nc),score)

plt.xticks(list(Nc))

print(plt.xticks())

plt.xlabel('Number of Clusters')

plt.ylabel('Score')

plt.title('Elbow Curve')

plt.show()

In [70]:

targets = apps['TARGET']
scores = np.empty(1)

for i in range(2,30):
    col_name = str(i)+' clusters'
    print(col_name)
    kmeans = KMeans(n_clusters=i)
    temp = kmeans.fit(scaled_app)
    temp_score = temp.score(scaled_app)
    temp_label = temp.labels_
    labels = pd.DataFrame(data = temp_label
                          ,columns = [str(i)+' clusters'])
    targets = pd.concat([targets,labels], axis=1)
    scores = np.append(scores,temp_score)
    
    print(scores)
    print(targets.sample(10))

2 clusters
[ 0.00000000e+00 -3.03873799e+08]
        TARGET  2 clusters
3680       NaN         1.0
251353     0.0         1.0
381186     0.0         NaN
391966     0.0         NaN
327227     0.0         1.0
284530     0.0         1.0
256784     0.0         1.0
210348     0.0         0.0
373543     0.0         NaN
307431     0.0         0.0
3 clusters
[ 0.00000000e+00 -3.03873799e+08 -2.90933049e+08]
        TARGET  2 clusters  3 clusters
451382     0.0         NaN         NaN
32614      NaN         1.0         1.0
346696     0.0         1.0         0.0
302106     0.0         1.0         0.0
387155     0.0         NaN         NaN
344350     0.0         1.0         0.0
268036     0.0         1.0         0.0
112069     0.0         1.0         0.0
321425     0.0         1.0         0.0
386998     0.0         NaN         NaN
4 clusters
[ 0.00000000e+00 -3.03873799e+08 -2.90933049e+08 -2.79975418e+08]
        TARGET  2 clusters  3 clusters  4 clusters
293725     0.0         1.0         0.0         1.0
294860     0.0         1.0         1.0         3.0
377764     0.0         NaN         NaN         NaN
325700     0.0         1.0         0.0         1.0
354461     0.0         1.0         0.0         1.0
57931      NaN         1.0         0.0         1.0
382931     0.0         NaN         NaN         NaN
56688      NaN         1.0         0.0         1.0
413528     0.0         NaN         NaN         NaN
445398     0.0         NaN         NaN         NaN

In [ ]:
targets = apps['TARGET']

kmeans = KMeans(n_clusters=10).fit(scaled_app)
score = kmeans.score(scaled_app)

In [11]:
labels = pd.DataFrame(data = kmeans.labels_
                          ,columns = ['clusters'])

targets = pd.concat([targets,labels], axis=1)



targets.head(10)

   TARGET  clusters  clusters
0     NaN       5.0       5.0
1     NaN       7.0       7.0
2     NaN       8.0       8.0
3     NaN       7.0       7.0
4     NaN       4.0       4.0
5     NaN       4.0       4.0
6     NaN       4.0       4.0
7     NaN       8.0       8.0
8     NaN       9.0       9.0
9     NaN       4.0       4.0

In [29]:
# '381186','387155','382931','377764'
# df.loc[df['column_name'] == some_value]
# nan_sample_apps = apps.iloc[apps['SK_ID_CURR'].isin('381186','387155','382931','377764')]

nan_sample_apps = apps.loc[[413528,445398,386998,387155,373543,391966,381186]]
nan_sample_apps.to_excel(pd.ExcelWriter('C:\\Users\\luken\\Documents\\Home Credit Group\\Data\\kmeans_error.xlsx'),'sheet1')
# [381186,387155,382931,377764,445398,456248]

# apps.index



# print(apps.columns.values)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """